steps:
  # Build a container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/clean-mountain-395906/testimage4', '.']


# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/clean-mountain-395906/testimage4']

